## Optimization exercise

**Goal: Train the 2nd order polynomial predictor using both gradient descent and stochastic gradient descent. Optimize the stepsizes and compare against scikit-learn's implementation.**

1. Download the data from [here](https://drive.google.com/file/d/0Bz9_0VdXvv9bUUNlUTVrMF9VcVU/view?usp=sharing).


2. Create a function psi(x), which transforms features AST (assists), REB (rebounds) and STL (steals) into 2nd order polynomial features (add each feature squared and each pair of features multiplied with every other)


3. Create a transformed data matrix X, where each x is mapped to psi(x).


4. Create a function p2(x,w), which outputs the value of the polynomial at x for given parameters w.


5. Create a function Loss(X,y,w), which computes the squared loss of predicting y from X by p2(x,w) using parameters w. Take variable PTS as y. We will predict scored points based on assists, rebounds and steals.


6. Code up the gradient descent. It should input a point w and a stepsize.


7. Choose an arbitrary point and stepsize. Run gradient descent for 100 iterations and compute the Loss after each iteration. How does the loss behave? Does it converge to something?


8. Can you find the stepsize, for which the loss is smallest after 100 iterations?

In [1]:
# IMPORT PACKAGES
import numpy as np
import pandas as pd

In [2]:
data_path = ''
nb = pd.read_csv(data_path+'nba_games_2013_2015.csv', delimiter=';')
x = nb[['AST','REB','STL']]
y = nb['PTS']

In [ ]:
PTS = w1*AST + w2*REB + w3*STL + w4*AST^2 + w5*REB^2 + w6*STL^2

In [61]:
print(x)
print(y)

      AST  REB  STL
0      41   43   14
1      23   43    8
2      20   39    7
3      19   47    6
4      21   43    4
...   ...  ...  ...
7375   17   39   10
7376   26   40   10
7377   23   52    8
7378   23   41   11
7379   17   44    4

[7380 rows x 3 columns]
0       144
1        92
2        98
3       101
4       110
       ... 
7375     87
7376    107
7377    116
7378     95
7379     97
Name: PTS, Length: 7380, dtype: int64


2. Create a function psi(x), which transforms features AST (assists), REB (rebounds) and STL (steals) into 2nd order polynomial features (add each feature squared and each pair of features multiplied with every other)

In [47]:
import copy

def psi(x):
    x_copy = copy.deepcopy(x)
    x_copy['AST_squared'] = x_copy['AST']**2
    x_copy['REB_squared'] = x_copy['REB']**2
    x_copy['STL_squared'] = x_copy['STL']**2
    x_copy['AST_REB'] = x_copy['AST'] * x_copy['REB']
    x_copy['AST_STL'] = x_copy['AST'] * x_copy['STL']
    x_copy['REB_STL'] = x_copy['REB'] * x_copy['STL']
    x_copy['1'] = 1

    return pd.DataFrame(x_copy)

3. Create a transformed data matrix X, where each x is mapped to psi(x).

In [48]:
X = psi(x)

In [50]:
X

AST  REB  STL  AST_squared  REB_squared  STL_squared  AST_REB  AST_STL  \
0      41   43   14         1681         1849          196     1763      574   
1      23   43    8          529         1849           64      989      184   
2      20   39    7          400         1521           49      780      140   
3      19   47    6          361         2209           36      893      114   
4      21   43    4          441         1849           16      903       84   
...   ...  ...  ...          ...          ...          ...      ...      ...   
7375   17   39   10          289         1521          100      663      170   
7376   26   40   10          676         1600          100     1040      260   
7377   23   52    8          529         2704           64     1196      184   
7378   23   41   11          529         1681          121      943      253   
7379   17   44    4          289         1936           16      748       68   

      REB_STL  1  
0         602  1  
1         344  1  
2         273  1  
3         282  1  
4         172  1  
...       ... ..  
7375      390  1  
7376      400  1  
7377      416  1  
7378      451  1  
7379      176  1  

[7380 rows x 10 columns]

4. Create a function p2(x,w), which outputs the value of the polynomial at x for given parameters w.

In [27]:
def p2(x, w):
    return (x * w).sum(axis=1)

In [51]:
p2(X, 2)

0       13528
1        8068
2        6460
3        7936
4        7068
        ...  
7375     6400
7376     8306
7377    10354
7378     8108
7379     6598
Length: 7380, dtype: int64

5. Create a function Loss(X,y,w), which computes the squared loss of predicting y from X by p2(x,w) using parameters w. 

Take variable PTS as y. We will predict scored points based on assists, rebounds and steals.

In [32]:
def loss(X, y, w):
    y_pred = p2(X, w)
    err = (y - y_pred).sum()
    return err**2

In [34]:
loss(X, y, 2)

3457025002053841

6. Code up the gradient descent. It should input a point w and a stepsize.

In [ ]:
def gradient_descent(w, stepsize):
    p(x, 2)

In [ ]:
#GRADIENT DESCENT

alpha = 0.01 #Step size
iterations = 2000 #No. of iterations
m = y.size #No. of data points
np.random.seed(123) #Set the seed
theta = np.random.rand(2) #Pick some random values to start with - we are estimating 2 coeficients: 1 for the variable and 1 for intercept

In [59]:
#GRADIENT DESCENT
def gradient_descent(x, y, theta, iterations, alpha):
    # prepare the empty lists for our history
    past_costs = []
    past_thetas = [theta]
    # repeating for number of iteration times
    for i in range(iterations):
        # computing of prediction. Dot product of coeficients and values
        prediction = np.dot(x, theta)
        # computation of error
        error = prediction - y
        # computation of overall cost for each iteration
        cost = 1/(2*y.size) * np.dot(error.T, error)
        past_costs.append(cost)
        # GRADIENT DESCENT part
        theta = theta - (alpha * (1/y.size) * np.dot(x.T, error))
        past_thetas.append(theta)
        
    return past_thetas, past_costs

7. Choose an arbitrary point and stepsize. Run gradient descent for 100 iterations and compute the Loss after each iteration. How does the loss behave? Does it converge to something?

In [60]:
gradient_descent(X, y, theta=np.ones(len(X.columns)), iterations=100, alpha=0.01)

<ipython-input-59-b1df825439a1>:16: RuntimeWarning: invalid value encountered in subtract
  theta = theta - (alpha * (1/y.size) * np.dot(x.T, error))


([array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
  array([-8.95451676e+02, -1.75042277e+03, -3.10335745e+02, -2.14408287e+04,
         -7.96955620e+04, -2.82012666e+03, -3.99382010e+04, -7.16723270e+03,
         -1.37652201e+04, -3.83388496e+01]),
  array([4.67612629e+07, 9.33697959e+07, 1.60609130e+07, 1.10436246e+09,
         4.28297887e+09, 1.42404260e+08, 2.10155418e+09, 3.64991368e+08,
         7.16630854e+08, 2.07942352e+06]),
  array([-2.49437016e+12, -4.98299320e+12, -8.56795711e+11, -5.88913425e+13,
         -2.28609821e+14, -7.59509715e+12, -1.12121144e+14, -1.94647242e+13,
         -3.82362075e+13, -1.10957733e+11]),
  array([1.33119928e+17, 2.65935874e+17, 4.57257423e+16, 3.14290093e+18,
         1.22006464e+19, 4.05336065e+17, 5.98371870e+18, 1.03879213e+18,
         2.04060878e+18, 5.92165089e+15]),
  array([-7.10443631e+21, -1.41926525e+22, -2.44032318e+21, -1.67732485e+23,
         -6.51132710e+23, -2.16322552e+22, -3.19343257e+23, -5.54389715e+22,
         -1.0890463

8. Can you find the stepsize, for which the loss is smallest after 100 iterations?